spring.application.name=clothing
# Ensure the database tables are created before running data.sql
spring.jpa.defer-datasource-initialization=true

# Optional: Set this to always if you want to see the SQL in your console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:h2:mem:clothingdb
spring.datasource.username=rhedgeadmin
spring.datasource.password=8ULIP3kvit11Pgyne2oPGa